// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrqoaevxlgligwisvotl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycW9hZXZ4bGdsaWd3aXN2b3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjE4NzAsImV4cCI6MjA3NDM5Nzg3MH0.m_d0dQW2_ExxOwcZYFBDu5Owjyiw48gO7hLtqWvqBSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});